### PR TITLE
SJRK-246: Removing the hardcoded about sections for the partners and …

### PR DESCRIPTION
**Pull request by michelled**
…switched to using the .Summary field.

### CODE REVIEW

**Comment by michelled** [comment]
Before I merge this I'd like some feedback in how the main Partners page and the individual partners pages look. @avtar or @dayotte

**Comment by dayotte** [comment]
Thanks @michelled,  I don’t think we need to repeat the About information on each partner’s page, since we have it on the main Partner’s page.

Also, I think we should replace the “SJRK Work” headings with “SJRK Project Contributions” for consistency (since that’s what the link says). 

There’s some headings formatting that I’d suggest, but it can probably wait - i.e. I think there should be different formatting for the H3’s - for example, “Environmental Guardians” and “Cuentalo” on FUTCO’s page should look different from "SJRK Project Contributions" heading - maybe they could just be lower case instead of all caps.

**Comment by michelled** [comment]
@dayotte, thanks for taking a look! I'll need to change how the 'About' works if we don't want it on the individual pages. I'll move it into the 'frontmatter' fields - you should still be able to edit those in Netlify.

**Comment by michelled** [comment]
I accidentally used the incorrect JIRA number in my branch and pull request so closing this in favour of: https://github.com/fluid-project/sojustrepairit.org/pull/58

**Pull request closed without merging**
