### PR TITLE
FLOE-527: Integrate UIO

### PR DESCRIPTION
**Pull request by grrrero**
This PR is to add UIO integration into the SJRK website.

### CODE REVIEW

**Comment by waharnum** [comment]
Hi @grrrero, thanks for this - I'm reviewing it today. 

Note - I've switched the base branch for the PR to `development` (where the docpad-based site code exists and where you did the work) from `master` (where the docpad-generated site code is committed currently).

**Comment by waharnum** [comment]
The image file `sjrk-nav-stroke-active-black.png` appears to be missing from the repo (attempts to load, but console reports a `404`, and "active" indicator does not appear in the base style or the black-text contrast styles) - can you add this file?

**Comment by waharnum** [comment]
Non-mobile navigation menu items are being cut off at large text sizes and narrower browser window widths - any way we can get them to spread out or not collapse on each other?

image

**Comment by grrrero** [comment]
Hey @waharnum, will look into it this afternoon!

**Comment by waharnum** [comment]
Thanks, those fixes look good! One other minor thing I'm seeing - can we get the continents inside the Oak Foundation logo at the appropriate contrast theme colors? 
image

Other than that things look good to me.

**Pull request merged**
